import os

TWITTER_CONSUMER_KEY = os.environ.get("TWITTER_CONSUMER_KEY", "")
TWITTER_CONSUMER_SECRET = os.environ.get("TWITTER_CONSUMER_SECRET", "")
TWITER_ACCESS_TOKEN = os.environ.get("TWITER_ACCESS_TOKEN", "")
TWITTER_ACCESS_TOKEN_SECRET = os.environ.get("TWITTER_ACCESS_TOKEN_SECRET", "")

TWITTER_CONSUMER_KEY_ALT = os.environ.get("TWITTER_CONSUMER_KEY_ALT", "")
TWITTER_CONSUMER_SECRET_ALT = os.environ.get("TWITTER_CONSUMER_SECRET_ALT", "")
TWITER_ACCESS_TOKEN_ALT = os.environ.get("TWITER_ACCESS_TOKEN_ALT", "")
TWITTER_ACCESS_TOKEN_SECRET_ALT = os.environ.get("TWITTER_ACCESS_TOKEN_SECRET_ALT", "")

# copied from twitter_config_sample.py

TWITER_ACCESS_TOKEN = "PLACEHOLDER"
TWITER_ACCESS_TOKEN_ALT = "PLACEHOLDER"

TWITTER_ACCESS_TOKEN_SECRET = "PLACEHOLDER"
TWITTER_ACCESS_TOKEN_SECRET_ALT = "PLACEHOLDER"

TWITTER_CONSUMER_KEY = "PLACEHOLDER"
TWITTER_CONSUMER_KEY_ALT = "PLACEHOLDER"

TWITTER_CONSUMER_SECRET = "PLACEHOLDER"
TWITTER_CONSUMER_SECRET_ALT = "PLACEHOLDER"
